### ISSUE TITLE
Discord Rich Presence not working.

### ISSUE THREAD

**Issue by XanderSo156** [Venipa/ytmdesktop2#1]
I have the settings necessary on in the app and discord but it doesn't work.

![image](https://user-images.githubusercontent.com/59516854/115651623-87924a80-a2f9-11eb-802d-76aab5e3cd25.png)

![image](https://user-images.githubusercontent.com/59516854/115651646-90831c00-a2f9-11eb-8ec7-82365178080a.png)

also side note check for update does not work either

**Comment by Venipa** [comment]
> I have the settings necessary on in the app and discord but it doesn't work.
> 
> ![image](https://user-images.githubusercontent.com/59516854/115651623-87924a80-a2f9-11eb-802d-76aab5e3cd25.png)
> 
> ![image](https://user-images.githubusercontent.com/59516854/115651646-90831c00-a2f9-11eb-8ec7-82365178080a.png)
> 
> also side note check for update does not work either

thanks for confirming, it wont work either for me, thats probably due to the shallow documentation of github action environment managing.

**Comment by XanderSo156** [comment]
hate to be the bearer of bad news, but discord rich integration still doesnt work. might be something on my end but might not be as well.

**Comment by Venipa** [comment]
> hate to be the bearer of bad news, but discord rich integration still doesnt work. might be something on my end but might not be as well.

no problem i've found the issue, fixing some redirect issues etc which should solve numerous issues after login

**Comment by XanderSo156** [comment]
Cool

**Comment by Venipa** [comment]
> Cool, ill test it out once you upload it.


v0.4.0 should be around the corner with many fixes ♥

**Comment by XanderSo156** [comment]
awesome, thanks! it seems the issue is fixed.
