### ISSUE TITLE
Add option to go to previous screen

### ISSUE THREAD

**Issue by Jeltel** [Venipa/ytmdesktop2#101]
**Is your feature request related to a problem? Please describe.**
When I browse Youtube Music searching for the right song/album/artist I frequently want to go back to the previous screen. However the standard options to go back a screen do not work. So no backspace Alt-< or the buttons on mouses or keyboards. 
There are also no buttons to back like in a browser.
So now I think what the last screen was and go back to that. Which is hard when it was a search result. I have to remember my search input and search for that again.

**Describe the solution you'd like**
A simple intuitive way to go back to the previous screen:

- Standard back buttons on keyboards, mouses etc work
- Back button in the interface

**Describe alternatives you've considered**
In the current version there seem to be no alternative besides remembering the last screen and manually go there.

**Additional context**

**Comment by Syhmac** [comment]
If you have back / forward button on your mouse, they work just fine. But alt+. and alt+, would be a good addition, that's true.

**Comment by SyntaxBreak** [comment]
Some options for going back that could be implemented:
- Back Button in UI (As mentioned earlier)
- Or the swipe to go back gesture that is present in most browsers.
