### ISSUE TITLE
Duplicate icon on taskbar / no icon at all

### ISSUE THREAD

**Issue by Syhmac** [Venipa/ytmdesktop2#102]
### Operating system

 Microsoft Windows [Version 10.0.22635.3286]

### YouTube Music Desktop App Version

v.0.11.6

### Bug description

There is a bug that causes you to show the duplicate of an app icon on taskbar when you have the app pinned there. It's also possible to make the app window open, but without any app button active on taskbar

## To get duplicate

1. Pin the icon to the taskbar.
2. Open the app from taskbar.
3. Close it ("Close window to tray instead of quitting" has to be checked in settings)
4. Open the app again from taskbar, there will be a duplicate icon created.

![image](https://github.com/Venipa/ytmdesktop2/assets/78266395/25d9eb5c-98de-48cd-81d6-e0b60ba7aa9a)

## To get no active window on taskbar

1. Pin the icon to the taskbar.
2. Open the app from taskbar.
3. Close it ("Close window to tray instead of quitting" has to be checked in settings)
4. Open the app from tray. Window will open but no active tab will be shown on the taskbar

![image](https://github.com/Venipa/ytmdesktop2/assets/78266395/bdd3ac32-26a5-4839-b67a-5f5952941a11)

## Windows 11 settings (in case they are relevant):

![image](https://github.com/Venipa/ytmdesktop2/assets/78266395/214b28a3-c481-4045-8c27-cedd4461520f)

![image](https://github.com/Venipa/ytmdesktop2/assets/78266395/3d4a17ed-d18b-4788-bf7a-76ad6781eded)

**Comment by Venipa** [comment]
been trying to reproduce both issues, no luck.
probably due the fact that im patching windows 11 taskbar to the appearance of windows 10 taskbar with ExplorerPatcher

**Comment by Syhmac** [comment]
Maybe. It's worth to mention that I'm also in Windows 11 insider's build and you are prob. on stable. And I'm not overwriting my taskbar with any software.
