### ISSUE TITLE
Discord Listen Along Functionality? / Better Sing Along Lyrics?

### ISSUE THREAD

**Issue by RaulIRC** [Venipa/ytmdesktop2#109]
Well I think that this program has solved a ton of issues I've been having with YouTube Music as a whole I think there are two features that would improve the listening experience for everyone. What do you think about adding a listen along function to discord rich prescence. And if possible, make the lyrics move similarly to the YouTube Music Mobile app?

**Comment by pokemonrocks9** [comment]
As an addition for the second portion, there is a javascript plugin for the website that kinda adds this if it could be implemented to the app
https://github.com/ProComGameS/ytm-lyrics-v2
