### ISSUE TITLE
Great start, just a few things i've noted...

### ISSUE THREAD

**Issue by adkeyz** [Venipa/ytmdesktop2#11]
Love this, especially as the other YTM app has seemingly been abandoned!

Just thought I'd punch in with a few things I have noticed.

- You can't close the app/minimise to the tray and keep the music playing, you need to keep it open on the Taskbar.
- The app's title isn't in the media controls notification on Win 11 (as seen in screenshots, compared to the old YTMD)
- "YouTube" has a capital T in the middle, it's not all lower case.
- I assume only Spotify has the ability to say "listening to" instead of "Playing a game" in Discord?

![No title](https://user-images.githubusercontent.com/40392408/157286905-488898e8-3740-4527-975c-08e9df09c140.png)
![Title](https://user-images.githubusercontent.com/40392408/157286909-d6b257b4-e003-4a8b-a5f8-93c18bcc24d5.png)

Keep up the great work, I look forward to updates!

**Comment by Exhabition** [comment]
Last one is correct, you can only do "Playing", Spotify just has more privileges :)

**Comment by Venipa** [comment]
> Last one is correct, you can only do "Playing", Spotify just has more privileges :)

bots have the privilege to use "listening to" afaik, i'll look into it.

**Comment by Exhabition** [comment]
> > Last one is correct, you can only do "Playing", Spotify just has more privileges :)
> 
> bots (we use discord rpc which is different) have the privilege to use "listening to" afaik, i'll look into it.

Selfbotting is against the Discord ToS :)

**Comment by Venipa** [comment]
> > > Last one is correct, you can only do "Playing", Spotify just has more privileges :)
> > 
> > 
> > bots (we use discord rpc which is different) have the privilege to use "listening to" afaik, i'll look into it.
> 
> Selfbotting is against the Discord ToS :)

ye i know but im talking about general bots & how to use it on discord rpc (not a self bot).

**Comment by Exhabition** [comment]
Bots != RPC, you can only use the playing state on user accounts with RPC

**Comment by Exhabition** [comment]
mhm, don't worry, I'm not attacking you or anything, just saying as far as I am aware it's not possible, and I did my fair share of RPC stuff

also I get that you are providing an example with that screenshot, but rich presence just work different for bots than for users, iirc, the ActivityType is ignored in requests by users?

**Comment by zapteryx** [comment]
> also I get that you are providing an example with that screenshot, but rich presence just work different for bots than for users, iirc, the ActivityType is ignored in requests by users?
yep, only bots have access to all statuses. users can only trigger `Listening to` by Spotify integration, and `Watching` by Activity (Watch Together) integration iirc. i don't even think it's actually possible for selfbots to have those custom status types apart from RPC tbh

**Comment by Justsnoopy30** [comment]
Couldn't you just fake spotify as the rpc source?
