### ISSUE TITLE
Retain size and position of Mini Player window after close (Open in Last Closed Position).

### ISSUE THREAD

**Issue by SyntaxBreak** [Venipa/ytmdesktop2#117]
As a person that constantly switches between the mini player and full page, I feel that it would be a nice QoL feature to retain the window's position and scaling after closing it. This could then be applied to again when minimising to the mini player, removing the need for constant readjustment.

Further, this could be expanded upon by making it an option in the app settings. Users could be able to choose whether or not they want the Mini Player to open in its last closed position.

Thanks for all the hardwork so far :D

**Comment by Venipa** [comment]
Implemented in the code structure refactor 👍
