### ISSUE TITLE
I want to Contribute

### ISSUE THREAD

**Issue by AniruddhaGawali** [Venipa/ytmdesktop2#118]
Hello I like your Idea of YouTube music application and I also like to contribute to this project can you please explain your file structure and how you are getting music from YouTube are you web scraping or using any API please also tell about how I can start contributing to this project

**Comment by Venipa** [comment]
There will be a file structure rework bundled with a electron update in the next weeks,
File structure will be mich better afterwards.

Stay tuned

**Comment by AniruddhaGawali** [comment]
Ok can you tell me the basic working of the application like how you are using YouTube music because I didn't see any api of YouTube music
