### ISSUE TITLE
Extended display area not rendered on resize until minimized and refocused

### ISSUE THREAD

**Issue by Justsnoopy30** [Venipa/ytmdesktop2#12]
![image](https://user-images.githubusercontent.com/33374736/159623612-00f0c895-df70-425a-a7f8-f2a059cb14d6.png)

**Comment by Venipa** [comment]
ec12246190f27e5261d05a6bf70f7dd7bc7a11b3 should fix it, you might want to try the latest release v0.5.6

**Comment by soko7awen** [comment]
This is still an issue for me. v0.12.17 on an AMD GPU.
