### ISSUE TITLE
Deprecated Discord RPC

### ISSUE THREAD

**Issue by danieleproia** [Venipa/ytmdesktop2#120]
### Operating system

Microsoft Windows [Versione 10.0.22631.3593]

### YouTube Music Desktop App Version

v0.12.11

### Bug description

Discord deprecated Discord RPC, in favor of [GameSDK](https://discord.com/developers/docs/game-sdk/getting-started)

So it doesn't work anymore

### Steps to reproduce

- Play track
- No rich presence even if enabled

**Comment by Venipa** [comment]
only the library has been deprecated, gamesdk still uses the activity of discord-rpc

![image](https://github.com/Venipa/ytmdesktop2/assets/17952364/8cb2caca-0b50-4c5d-8d6b-70de78be64de)

still works but i'll migrate once libraries have been made

**Comment by danieleproia** [comment]
Okay, so it's probably a me issue, sorry! Closing the issue
