### ISSUE TITLE
DMG is damaged

### ISSUE THREAD

**Issue by scoobisofficial** [Venipa/ytmdesktop2#126]
### Operating system

MacOS Sonoma 14.5

### YouTube Music Desktop App Version

0.12.11

### Bug description

DMG is damaged and cannot open the Updater

### Steps to reproduce

1. Download DMG
2. Open
3. Disappointment

### Relevant log output

```shell
“YouTube Music for Desktop” is damaged and can’t be opened. You should eject the disk image.
This item is on the disk image “YouTube-Music-for-Desktop-0.12.11-arm64.dmg”. Chrome downloaded this disk image today at 7:03 PM.
```

**Comment by Venipa** [comment]
Apple Silicon Builds need to run this command after installing:
`xattr -dr com.apple.quarantine /Applications/YouTube\ Music\ for\ Desktop.app`

until i pay ($99+) for a apple license

**Comment by scoobisofficial** [comment]
I decided to download the non arm64 version and it works perfectly. Great work you're doing.
