### ISSUE TITLE
rpc is not working and no custom interface

### ISSUE THREAD

**Issue by tiktakgames** [Venipa/ytmdesktop2#16]
![image](https://user-images.githubusercontent.com/74923138/160130261-4cba56c1-fd2a-4338-80a0-2ae46b4e71af.png)
^ no custom interface ^
![image](https://user-images.githubusercontent.com/74923138/160130401-a587d702-c6e5-41be-930d-225b3bbc405c.png)
^ no discord rpc when its enabled and music is playing ^

**Comment by tiktakgames** [comment]
> Which OS are you using?
> 
> If windows, try to running the app and/or discord as administrator

still no rpc

**Comment by tiktakgames** [comment]
@Venipa

**Comment by tiktakgames** [comment]
maybe its because i have betterdiscord?

**Comment by Venipa** [comment]
shouldn't be an issue with betterdiscord, windows probably acting up on transporting that rpc connection even though it says its connected.
It mostly settles with just restarting ytmdesktop2 as admin and/or restart your pc.

**Comment by tiktakgames** [comment]
i reinstalled windows, restarted yt music as admin and still no rpc
