### ISSUE TITLE
Can not log in 

### ISSUE THREAD

**Issue by sandroshu** [Venipa/ytmdesktop2#20]
### Operating system

Windows 11 22000.613

### Youtube Music Desktop App Version

0.5.4

### Bug description

Couldn’t sign you in
This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en)
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

### Steps to reproduce

Click login
Type username
Press enter or click next

**Comment by Venipa** [comment]
https://github.com/Venipa/ytmdesktop2/issues/9
