### ISSUE TITLE
Can't switch to brand account 

### ISSUE THREAD

**Issue by synesta** [Venipa/ytmdesktop2#21]
### Operating system

Microsoft Windows 11 Home 10.0.22000 Build 22000

### Youtube Music Desktop App Version

v0.5.4

### Bug description

https://user-images.githubusercontent.com/72947065/165878512-43145c89-bf0a-41ea-88ee-867c004650c1.mp4

Can't switch to brand account while in the app, all links in this menu work except this one, restarting PC and the app itself hasn't fixed

### Steps to reproduce

Click on profile icon
Click switch account

**Comment by Venipa** [comment]
you'll need to press the logout button, once you've done it you can switch accounts from google's page sign in page.

**Comment by DocN** [comment]
@Venipa You don't get to pick one of your YouTube accounts on sign-in, it just defaults to to your first one. 

I found a work around for this.
- Click on Manage your Google Account from the account dropdown
- Open the dev console under view -> developer tools and type location.href= "https://www.youtube.com"
- Change your account on YouTube in the browser window, close the window and restart the app.
