### ISSUE TITLE
album cover

### ISSUE THREAD

**Issue by senolfndk** [Venipa/ytmdesktop2#22]
Can you add the album cover of the song playing? 
![Ekran görüntüsü 2022-05-08 234603](https://user-images.githubusercontent.com/52818836/167315265-68d906a6-93a6-4c91-a3d3-d85eb0c6a971.png)
![Ekran görüntüsü 2022-05-08 234649](https://user-images.githubusercontent.com/52818836/167315266-7235cd3c-1415-4b67-9883-6cfe4ab23be7.png)
![Ekran görüntüsü 2022-05-08 234743](https://user-images.githubusercontent.com/52818836/167315267-e60498f4-b2f8-40f9-a4ba-309b8b3471e1.png)

**Comment by Venipa** [comment]
already in there.
![image](https://user-images.githubusercontent.com/17952364/167315323-cd0c83c2-0716-4bfe-8c9e-074015e2fad6.png)
