### ISSUE TITLE
Issues during first load after reboot

### ISSUE THREAD

**Issue by jitoxx** [Venipa/ytmdesktop2#23]
### Operating system

Microsoft Windows 11

### Youtube Music Desktop App Version

v0.5.5

### Bug description

After Rebooting the PC, the app has issues to load the homepage and i must wait 1 minute to load

### Steps to reproduce

On Windows 11: Only Reboot the PC after Installation and the app is stuck.

**Comment by Venipa** [comment]
ec12246190f27e5261d05a6bf70f7dd7bc7a11b3 should fix it
