### ISSUE TITLE
Go back / back button

### ISSUE THREAD

**Issue by renaldoaluska** [Venipa/ytmdesktop2#24]
Is there any way to go back? Or any plan on adding back button? Thank you

**Comment by Venipa** [comment]
what do you mean? where do you want a back button?

**Comment by renaldoaluska** [comment]
A button to go back to the previous page (browser navigation). Somewhere around the upper left?

**Comment by Venipa** [comment]
> A button to go back to the previous page (browser navigation). Somewhere around the upper left?

there should be a home button if you navigate away from music.youtube.com
![image](https://user-images.githubusercontent.com/17952364/169158355-a3848cf9-4e9a-459c-a45d-59d5a31977a5.png)
