### ISSUE TITLE
Remove DRP While Idle

### ISSUE THREAD

**Issue by BuzzfeedBlue** [Venipa/ytmdesktop2#26]
I am glad that discord rich presence is integrated, but when I have the program minimized and either no song playing or a song is paused I think it would make sense to have discord rich presence stop displaying that I am playing youtube music.

If this doesnt fit your idea for the program, it could also be a toggle in the discord section of options.

Also, bump for a mini player. Steal some code from the other desktop music player ;)

**Comment by Venipa** [comment]
@BuzzfeedBlue pre-release 0.7.0 contains the idle checker, after 5 minutes of idling discord, rpc will be stopped (until user is focuses the window again)
