### ISSUE TITLE
I am a massive idiot

### ISSUE THREAD

**Issue by IGS-GIT** [Venipa/ytmdesktop2#27]
So this is definitely user error, but I can't seem to get OBS to detect my songs. I've got Snip going and have moved all the necessary files into Snip's folder. I have added the browser source and formatted it to work with the plugin. I am still getting nothing displaying. Sorry if this is dumb, just really want it to work and love what ur doing :)

**Comment by Venipa** [comment]
ye because snip isnt required here or rather not supported, you'll need to enable the api in the ytmdesktop2 settings & load the html into a browser source.

Extract zyphens modded html files and open the song.html in the browser source.
![image](https://user-images.githubusercontent.com/17952364/180310934-caed2628-0312-43de-b229-dfa48f669cd8.png)

**Comment by IGS-GIT** [comment]
I have the API enabled. 
![image](https://user-images.githubusercontent.com/55769536/180311115-29c14310-feec-422f-ac5f-4484843f184c.png)

I extracted the HTML files and made a source directing to the song.html file
![image](https://user-images.githubusercontent.com/55769536/180311531-5a04c55c-b070-4d41-8f12-312734e9abad.png)
![image](https://user-images.githubusercontent.com/55769536/180311670-8262d1eb-5b91-44c5-ae25-6f00413a0af5.png)


It's still not displaying. I am not sure what I'm missing

**Comment by Venipa** [comment]
i'll look into it, seems to not start somehow

**Comment by IGS-GIT** [comment]
sorry to bother but any update? it may still be user error. not sure how the HTML file is supposed to find my YTM instance.

**Comment by CamillePele** [comment]
I have the same problem and I noticed this error in the Chrome console
**GET http://localhost:13091/track net::ERR_FAILED 200**
**Access to XMLHttpRequest at 'http://localhost:13091/track' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.**
I don't know much about web but it seems to be on the side of ytmdesktop2

**Comment by IGS-GIT** [comment]
> I have the same problem and I noticed this error in the Chrome console
> **GET http://localhost:13091/track net::ERR_FAILED 200**
> **Access to XMLHttpRequest at 'http://localhost:13091/track' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.**
> I don't know much about web but it seems to be on the side of ytmdesktop2

Might have something to do with admin privileges. Try launching in admin mode

**Comment by Venipa** [comment]
@CamillePele @IGS-GIT 
to fix this issue start obs with `--disable-web-security` which also disables cors enforcement
just add it to the shortcut on the desktop or startmenu
![image](https://user-images.githubusercontent.com/17952364/207990863-535183f1-dd23-4f6f-ab91-10367e9d17f8.png)
