### ISSUE TITLE
Maximizing window on Linux not rendering properly

### ISSUE THREAD

**Issue by tannishpage** [Venipa/ytmdesktop2#3]
It looks fine before maximizing:
![image](https://user-images.githubusercontent.com/32695750/129114373-083e262a-f84e-4960-81b4-92d6cba1f9dd.png)

Has whitespace on the right and bottom after maximizing
![image](https://user-images.githubusercontent.com/32695750/129114399-8039b15c-144f-4a27-a9d7-078d5229a8cf.png)

I'm running Elementary OS 6, I am using the .Appimage file from the latest release 0.4.9

**Comment by Fauzanmhr** [comment]
![Screenshot from 2023-03-27 09-02-19](https://user-images.githubusercontent.com/105500225/227823476-bfa3b404-6c0e-4fea-a2ed-da63f0e2fee6.png)
hahaa still same on last update but keep  up the enthusiasm for the developer (im using latest pop os)
