### ISSUE TITLE
media keys not working on linux

### ISSUE THREAD

**Issue by ghost** [Venipa/ytmdesktop2#30]
### Operating system

Ubuntu 22.04.1 LTS

### YouTube Music Desktop App Version

v0.7.7

### Bug description

When listening to music, the play, fast forward, and rewind media keys on the keyboard do not control the app.

### Steps to reproduce

Play a song, and click either fast forward, rewind, or play

**Comment by Venipa** [comment]
its fixed in v0.9.5
