### ISSUE TITLE
Add Volume Slider to MiniPlayer 🔊

### ISSUE THREAD

**Issue by Jih-o** [Venipa/ytmdesktop2#31]
**Is your feature request related to a problem? Please describe.**
I like MiniPlayer  but i cannot control volume in it 😢

**Describe the solution you'd like**
Add volume slider to MiniPlayer 

**Describe alternatives you've considered**
🤷

**Additional context**
🤔 Any ideas on supporting custom CSS in the MiniPlayer as well?

**Comment by Venipa** [comment]
will be added, still in beta tho
