### ISSUE TITLE
Unsecure browser

### ISSUE THREAD

**Issue by EgguMan** [Venipa/ytmdesktop2#32]
### Operating system

Microsoft Windows [Version 10.0.19044.1826]

### YouTube Music Desktop App Version

v0.8.6

### Bug description

When I go to sign in, google tells me the browser is unsecure.

### Steps to reproduce

click sign in, type email press confirm

**Comment by Venipa** [comment]
There should be a button to "try again". Its an restriction that will be fixed in the future.
