### ISSUE TITLE
Can't play music again after pausing

### ISSUE THREAD

**Issue by counterfeited** [Venipa/ytmdesktop2#34]
### Operating system

Win 10 Version 21H2 (19044.1826)

### YouTube Music Desktop App Version

v0.8.6

### Bug description

While using the Mini-Player, if you pause, you cannot click it again and start playback, furthermore, the pause button (ideally) would turn into a Play button icon.

FN keys also do not work while using Mini-Player

### Steps to reproduce

https://user-images.githubusercontent.com/105516669/184135867-fb437c83-eceb-4057-8a7f-ca00095a0e4a.mp4

**Comment by creativegamer03** [comment]
In addition to this:
After manually resuming paused playback from the main window and returning back to the mini player, it somewhat works again. However, if left paused for a long time, it would turn into a pause button, while paused.
