### ISSUE TITLE
I Can't Access Age Restricted Videos On The Client

### ISSUE THREAD

**Issue by pofdzm** [Venipa/ytmdesktop2#37]
### Operating system

Microsoft Windows [Version 10.0.19043.1889]

### YouTube Music Desktop App Version

0.8.6

### Bug description

I Can't Access Age Restricted Videos On The Client, I press the "I Understand And Want To Continue" button but it doesn't skip

### Steps to reproduce

Open an age restricted video, that's it

### Relevant log output

```shell
There isn't a log output in "C:\Users\PC\AppData\Local\Programs\YouTube Music for Desktop"
```

**Comment by pofdzm** [comment]
![image](https://user-images.githubusercontent.com/63299895/186265028-bc7ca7f8-5029-466e-801e-ab00f79ba520.png)
Pressing it just doesn't work

**Comment by Venipa** [comment]
for now just sign in on the top right
![image](https://user-images.githubusercontent.com/17952364/186279306-bddc77cf-7d70-47a8-a2af-d0901b5e2724.png)
