### ISSUE TITLE
Window not remembering size and position

### ISSUE THREAD

**Issue by Frio-niel** [Venipa/ytmdesktop2#38]
### Operating system

 Microsoft Windows [Version 10.0.22000.918]

### YouTube Music Desktop App Version

v0.8.6

### Bug description

Every time I open the app the window size and position resets. I can't be the only one facing this issue, right?

### Steps to reproduce

Restart the app

**Comment by Sickjuicy** [comment]
Same issue

**Comment by Jaluvshuskies** [comment]
Same here. Issue persists on reboot, and also across both multiple and the same monitor

Windows 10 
`Version	10.0.19045 Build 19045`

YouTube Music Desktop App Version
`v0.10.9`

**Comment by Venipa** [comment]
feature has been introduced in v0.10.11

**Comment by Sickjuicy** [comment]
There is a problem with the Windows zoom for screens.
I have a monitor set to 150% zoom (Scaling), but when I reopen the app, it displays too large. 

Steps to reproduce
Set the Screen zoom (Scaling) to more than 100% and restart the App.
