### ISSUE TITLE
Unsupported Browser

### ISSUE THREAD

**Issue by Cannabis-CFG** [Venipa/ytmdesktop2#39]
### Operating system

Microsoft Windows Version 21H2 (OS Build 19044.2006)

### YouTube Music Desktop App Version

v0.8.6

### Bug description

Unable to sign in to my Google account to listen to my list of music.

### Steps to reproduce

Download latest release, install, and click sign in,

**Comment by marcandreappel** [comment]
I had the same issue with a workaround:

1. On the Google page with the failed login attempt, click on the link "Read more" of the error message.
2. On the new window that just opened, click on the "Sign in" button ; do sign in.
3. Reload the Player Window and the sessions is open.

**Operating system**
Arch Linux

**YouTube Music Desktop App Version**
v0.8.6

**Bug description**
Unable to sign in to my Google account to listen to my list of music.

**Steps to reproduce**
Download latest release as AppImage, install with AppImageLauncher, open and click sign in

Relevant log output
No response

**Comment by marcandreappel** [comment]
Else the solution in issue #9 might work as well…

**Comment by Cannabis-CFG** [comment]
> Else the solution in issue #9 might work as well…

Reinstalling v0.8.6 and letting it update to v0.8.7 has solved this issue, unsure if this is still true for others.

**Comment by Sebasee009** [comment]
I found the problem, it causes Custom CSS to display like this, disabled it and went to the signup page again and it worked.
