### ISSUE TITLE
mini-player requests

### ISSUE THREAD

**Issue by counterfeited** [Venipa/ytmdesktop2#40]
**Is your feature request related to a problem? Please describe.**
The requests are not related to any problems, they're just QoL suggestions.

**Describe the solution you'd like**
- There should be a dislike button to match the [like button](https://i.imgur.com/NyPrfvi.png), we still should be able to control what gets recommended to us while in mini-player.
- The [fullscreen button](https://i.imgur.com/mi1MvyC.png) should bring you back to the normal view, as there's no actual way to go back to normal view from the mini player
- [Album covers](https://i.imgur.com/BSUq31Q.png), no matter which as far as I can tell, are being forced to be a certain dimension which absolutely ruins quality, maybe do something like display the album with some transparency (like how it is right now, but more visible) in the background
- View current song/album cover in fullscreen / web
- [Song title](https://i.imgur.com/xuRSB0X.png) should take priority over the artist's name, song title is more important and usually want people are going to be looking at in the mini-player

**Comment by counterfeited** [comment]
Also worth mentioning that there is no ability to interact with this slider on the mini-player, so it solely serves as an indicator which kind of sucks, it'd be cool to be able to drag this.

https://i.imgur.com/pzqzGl9.png

**Comment by Venipa** [comment]
also decided to add accents (picked from thumbnail)

![image](https://user-images.githubusercontent.com/17952364/199158229-d233d330-17bb-401e-aedf-c3692c926295.png)
