### ISSUE TITLE
Media Keys & Media Notification Not Working

### ISSUE THREAD

**Issue by adkeyz** [Venipa/ytmdesktop2#41]
On the latest version 0.8.7, the media keys for next track and previous track do not work.

The media control notification also does not work,

Windows 11.

**Comment by xdn3** [comment]
Same here. Windows 11 22H2.

**Comment by ilhamtrz** [comment]
same here. I'm using Windows 10 21H1

**Comment by farsdewibs0n** [comment]
Doesnt show up on Windows 10 22H2, probably not implemented yet

**Comment by Venipa** [comment]
it is implemented but there has been issues with xosms, probably planning to replace it in the future

**Comment by Venipa** [comment]
its fixed in v0.9.5
