### ISSUE TITLE
Autoplay not working

### ISSUE THREAD

**Issue by tasawe** [Venipa/ytmdesktop2#43]
### Operating system

Microsoft Windows 10

### YouTube Music Desktop App Version

v0.9.0

### Bug description

When listening to a song, autoplay doesn't work, and the song just plays in loop. Doesn't happen on "listen again", as a queue is automatically created.

### Steps to reproduce

- Search for a song
- Click on play
- Skip to the end of the song
- The song will start over

**Comment by Venipa** [comment]
not an issue on this unofficial desktop app, you might want to send a ticket to youtube music for this.

**Comment by tasawe** [comment]
Not an issue on youtube music. When autoplay on, the app should add songs to the end of the queue.
On youtube music, when the queue ends and autoplay is on, a song is added to the queue:
![screenshot1](https://user-images.githubusercontent.com/71244441/203664780-a0591a70-2999-478b-b5d7-eeedf96f542a.png)
On the desktop app, the song doesn't get added and the queue restarts:
![image](https://user-images.githubusercontent.com/71244441/203664796-4bb9cd83-bcba-4d86-9911-0cca72b61e78.png)
