### ISSUE TITLE
When autoplay on, the app should add songs to the end of the queue

### ISSUE THREAD

**Issue by tasawe** [Venipa/ytmdesktop2#44]
Not an issue on youtube music. When autoplay on, the app should add songs to the end of the queue.
On youtube music, when the queue ends and autoplay is on, a song is added to the queue:
![screenshot1](https://user-images.githubusercontent.com/71244441/203664780-a0591a70-2999-478b-b5d7-eeedf96f542a.png)
On the desktop app, the song doesn't get added and the queue restarts:
![image](https://user-images.githubusercontent.com/71244441/203664796-4bb9cd83-bcba-4d86-9911-0cca72b61e78.png)

_Originally posted by @tasawe in https://github.com/Venipa/ytmdesktop2/issues/43#issuecomment-1325777354_
      

This is an issue only on the desktop app.

**Comment by Venipa** [comment]
can you show me the full vertical on the playlist?
![image](https://user-images.githubusercontent.com/17952364/203665804-72783d8a-16f4-42d7-b5c6-07a3b3564c18.png)

if autoplay is on there should be a list on the bottom which gets added, if there isnt than its not a eligible playlist for autoplay

**Comment by tasawe** [comment]
![image](https://user-images.githubusercontent.com/71244441/203666333-f5a9b502-fcc9-4e88-bb5a-cf07145232af.png)

**Comment by tasawe** [comment]
just realized i had the replay option on, not really an issue
