### ISSUE TITLE
Change resolution

### ISSUE THREAD

**Issue by ZombieAnidata** [Venipa/ytmdesktop2#47]
When i am watching an MV the videos quality is always set on the lowest option and the video it's pixelated  

There should be an option that forces the video to a higher resolution like some extensions on Chrome or Firefox.
 
1: First photo on the YT Music client:
![image](https://user-images.githubusercontent.com/64793241/210158273-726239e6-eb6d-4cec-a3bb-809f5378781d.png)
2: Second image on browser with extension that forces the resolution at 1080P:
![image](https://user-images.githubusercontent.com/64793241/210158290-72c40381-b633-40e5-942c-193bbdb15967.png)

**Comment by Venipa** [comment]
@ZombieAnidata whats the extension name used?

**Comment by ZombieAnidata** [comment]
The extension that i use is called YouTube High Resolution. https://addons.mozilla.org/en-US/firefox/addon/youtube-high-definition/

**Comment by Venipa** [comment]
Ye I'm already implementing it

**Comment by Venipa** [comment]
@ZombieAnidata implemented in v0.10.9
