### ISSUE TITLE
Last.FM integration

### ISSUE THREAD

**Issue by Rynach** [Venipa/ytmdesktop2#5]
As a long-time user of Last.FM it would be nice if this app had support for scrobbling played songs. This would be good and a nice addition in terms of integration, as this app already supports Discord.

**Comment by Venipa** [comment]
![image-3](https://user-images.githubusercontent.com/17952364/212449216-f2d632c7-f0cc-4822-9b2e-6ac7bd5aa806.png)
![image-2](https://user-images.githubusercontent.com/17952364/212449220-38bffaec-196e-4e40-94f1-5c4200f8885c.png)

Recently started working on it 👍

**Comment by Venipa** [comment]
LastFM is in the latest version [v0.10.2](https://github.com/Venipa/ytmdesktop2/releases/v0.10.2/)
@phendrome @Rynach
