### ISSUE TITLE
Last.fm needs to reauthenticate every time the app is closed

### ISSUE THREAD

**Issue by DrinkingJoe** [Venipa/ytmdesktop2#50]
### Operating system

 Microsoft Windows [Version 10.0.22621.1105]

### YouTube Music Desktop App Version

v0.10.2

### Bug description

Last.fm needs to be authenticated again after the app is closed and reopened

**Comment by Venipa** [comment]
i've been using it for days without issues, after you authenticate there should be a success window from lastfm, wait up until it closes automatically.

a video record would be very appreciated, getsharex.com or via "obs"

**Comment by DrinkingJoe** [comment]
https://imgur.com/a/5qbSRhg
When I authenticate it, it works fine. But when I close it, it needs to be re-authenticated in order for the scribbling to work

**Comment by Venipa** [comment]
could you check if there are any keys saved under credential manager named with "ytmdesktop2/"

open "credential manager" > windows credentials > check for keys starting with ytmdesktop2 and check if they are not empty.
(do not share the session or token publicly)

**Comment by Venipa** [comment]
@DrinkingJoe v0.10.3 has been released, adjusted some things in that version

**Comment by DrinkingJoe** [comment]
![image](https://user-images.githubusercontent.com/63132234/213039424-8f833a84-0337-4d22-8e1b-6058be5030fc.png)
They are not empty. Issue persists after the update

**Comment by Zer0Key** [comment]
Can confirm this issue persists in v0.10.4. My credential manager looks the same as Joe's.

**Comment by Venipa** [comment]
for now connect to lastfm from settings window > integrations tab

**Comment by Venipa** [comment]
fixed in v0.10.5
