### ISSUE TITLE
Up next list laggy

### ISSUE THREAD

**Issue by xdn3** [Venipa/ytmdesktop2#53]
The up next list is laggy, as seen in the video below. Same applies with rearranging songs.
(Sorry for bad quality video)

https://user-images.githubusercontent.com/86706790/214259836-639a7cae-6f08-4186-bbaa-85c6168060c8.mp4

**Comment by Venipa** [comment]
this issue is from youtube/google, might take a while until google realizes that their app is lagging if being used for a long time.

**Comment by xdn3** [comment]
Update: I just noticed that if I disable custom css the issue is resolve. I really like the custom css, so please look into it.
Thanks.
