### ISSUE TITLE
Play/Pause Media controls no longer working

### ISSUE THREAD

**Issue by omnigamer87** [Venipa/ytmdesktop2#59]
### Operating system

 Microsoft Windows [Version 10.0.22621.1194]

### YouTube Music Desktop App Version

0.10.9

### Bug description

I'm currently using a Stream Deck + and the built-in play/pause and skip track features are awesome to have. Since the update, the skip track functionality still works, but will no longer play/pause.

**Comment by laxity7** [comment]
duplicate https://github.com/Venipa/ytmdesktop2/issues/45
