### ISSUE TITLE
Discord rich presence not working ? 

### ISSUE THREAD

**Issue by StarBleu1** [Venipa/ytmdesktop2#6]
Discord rich presence not working for me ( turned option both in client and discord)

**Comment by Venipa** [comment]
what windows version are you using?

**Comment by StarBleu1** [comment]
10 Pro 10.0.19043

**Comment by Venipa** [comment]
> 10 Pro 10.0.19043 Also I downloaded from website not GitHub if that's relevant

might need to run ytmdesktop as administrator

**Comment by StarBleu1** [comment]
Tried that and nothing.  Also is it compatible with better discord I forgot I am using it and that may be the issue

**Comment by Venipa** [comment]
does it show a checkmark on the discord icon? 
![image](https://user-images.githubusercontent.com/17952364/149237115-03ca7afb-01c8-4ac0-b5f2-57022844abe0.png)

**Comment by StarBleu1** [comment]
couldnt find that button in version from https://ytmdesktop.app/ , downloaded from github now and everything is working ty for help

**Comment by Venipa** [comment]
@StarBleu1 

![](https://cdn.discordapp.com/emojis/414559254305832970.webp?size=96&quality=lossless)

ytmdesktop**2** is https://youtube-music.app/
ytmdesktop is a different project from a different developer
