### ISSUE TITLE
UI Performance is a Slog

### ISSUE THREAD

**Issue by IGS-GIT** [Venipa/ytmdesktop2#62]
### Operating system

Windows 11 22H2

### YouTube Music Desktop App Version

v0.10.9

### Bug description

When viewing user generated content (ie. playlists or saved albums) the whole UI slows down and becomes unusable. It's only snappy and usable on the home page. Is this something you could fix or is it just an electron limitation?

### Steps to reproduce

Using the program :)

**Comment by Aasikki** [comment]
Can confirm, changing volume or seeking is horrible.

**Comment by Venipa** [comment]
> Here's something I've discovered. It depends on how many songs are in the playlist/album. My playlist has over 150 songs in it and the performance tanks dramatically. I viewed an ablum with 6 songs and the performance only slightly changed but was usable. Theres definitely something wrong with caching

its a known issue with youtube music's website, unless google/youtube recognizes this issue it wont be fixed anytime soon.

**Comment by IGS-GIT** [comment]
> > Here's something I've discovered. It depends on how many songs are in the playlist/album. My playlist has over 150 songs in it and the performance tanks dramatically. I viewed an ablum with 6 songs and the performance only slightly changed but was usable. Theres definitely something wrong with caching
> 
> its a known issue with youtube music's website, unless google/youtube recognizes this issue it wont be fixed anytime soon.

ah that makes sense. ill try putting in a bug report and hopefully they get off their ass

**Comment by Aasikki** [comment]
> > Here's something I've discovered. It depends on how many songs are in the playlist/album. My playlist has over 150 songs in it and the performance tanks dramatically. I viewed an ablum with 6 songs and the performance only slightly changed but was usable. Theres definitely something wrong with caching
> 
> its a known issue with youtube music's website, unless google/youtube recognizes this issue it wont be fixed anytime soon.

Is that really so? Works perfectly in Firefox for me.

**Comment by DarkZoomy** [comment]
I tested it with Firefox (112.0.1) and Chrome (112.0.5615.138) and both worked perfectly fine. Tested with a playlist with 286 items and no lags at all.

**Comment by EdgardoSchiffer** [comment]
Hi everybody, I have the same issue that UI becames unusable with YT Music Desktop, so searching in the repo I ended in this thread and read the answer that says its due to playlist size and that it is due to YT Music itself so I went to try on music.youtube.com for a whole day, but it wasn't the same experience than on app, it is true that it is kinda slow but not as much than on YT Music Desktop. 

I started to look at app settings and found that Custom CSS makes that difference, inmediately after disabling it performance improved a lot. For both versions I tried the same playlist that has 350 songs, there may be some optimization that could be on custom CSS engine (if it could be called this way).

**Comment by xdn3** [comment]
> > Here's something I've discovered. It depends on how many songs are in the playlist/album. My playlist has over 150 songs in it and the performance tanks dramatically. I viewed an ablum with 6 songs and the performance only slightly changed but was usable. Theres definitely something wrong with caching
> 
> its a known issue with youtube music's website, unless google/youtube recognizes this issue it wont be fixed anytime soon.

I have noticed that disabling the custom CSS (the one provided with the install) fixes the performance problems.

**Comment by Aasikki** [comment]
> > > Here's something I've discovered. It depends on how many songs are in the playlist/album. My playlist has over 150 songs in it and the performance tanks dramatically. I viewed an ablum with 6 songs and the performance only slightly changed but was usable. Theres definitely something wrong with caching
> > 
> > 
> > its a known issue with youtube music's website, unless google/youtube recognizes this issue it wont be fixed anytime soon.
> 
> I have noticed that disabling the custom CSS (the one provided with the install) fixes the performance problems.

I still have horrible performance with custom css off.

**Comment by IGS-GIT** [comment]
The issue still persists with the latest public version, but I'd have to guess it's an issue with YouTube music itself. Until Google makes an effort to optimize its website, It's going to stay that way.
