### ISSUE TITLE
Search Screen Issue

### ISSUE THREAD

**Issue by p1an2ed** [Venipa/ytmdesktop2#65]
![resim](https://user-images.githubusercontent.com/82164977/227030017-5bc20275-9b7f-4795-82e9-017049cf8b4b.png)

**Operating system**

Windows 10 Pro

**YouTube Music Desktop App Version**

v0.10.11

**Bug description**

This always happen when I search some music

**Steps to reproduce**

Using the search tab

**Comment by Venipa** [comment]
delete the folder at Documents called "ytmdesktop", relaunch ytmdesktop afterwards
