### ISSUE TITLE
blank black screen when startup

### ISSUE THREAD

**Issue by GigiBL** [Venipa/ytmdesktop2#68]
### Operating system

windows 11 home 22h2

### YouTube Music Desktop App Version

YouTube-Music-for-Desktop-Setup-0.10.11_2

### Bug description

just starts off blank blank screen nothing else when start up 
![ScreenShot_20230419143358](https://user-images.githubusercontent.com/28859232/233168354-79969b4d-4f80-49a6-8bbb-249d9620a849.jpeg)

### Steps to reproduce

i honestly dont know other than to get it to load start up would love to try it as looking for something like this!

**Comment by GigiBL** [comment]
![image](https://user-images.githubusercontent.com/28859232/233168803-0b701f35-1b78-4c40-a3a9-b7d929c549a1.png)

**Comment by EmRodr** [comment]
I'm having the same issue. My PC has Windows 10. Restarting the application seems to fix it temporarily, but keeps happening very often.
