### ISSUE TITLE
Change "Playing" to "Listening" on Discord Rich Presence integration

### ISSUE THREAD

**Issue by paulocavallari** [Venipa/ytmdesktop2#70]
In the new version of Discord integration API called "Discord Game SDK" you can change a "Playing" text to "Streaming", "Listening" or some custom one.

More info here:
https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum

**Comment by Pyseph** [comment]
Sadly this isn't possible due to Discord limitations, as written below the link you sent:
> `ActivityType` is strictly for the purpose of handling events that you receive from Discord; though the SDK/our API will not reject a payload with an ActivityType sent, it will be discarded and will not change anything in the client.

**Comment by starstriker0** [comment]
uh, i have a suggestion, and this is just a suggestion from someone who doesnt know too much about this so dont bite my head off if its a dumb one.

right now, in vencord, there is a plugin called custom rpc, witht hat oyu can set whatever status you want, listening, watching, streaming, etc. what if you made a sort of companion plugin for vencord or better discord, would it be possible to link the "youtube music for desktop" data to that plugin and have the plugin display what you want it to?

**Comment by Pyseph** [comment]
Hello! It actually does seem to be possible, as another google chrome extension has achieved it (https://chromewebstore.google.com/detail/watchdis/fdlcfnimjmkjlajpifhnehgeeiipgmfm?hl=en-US).
Perusing its source code, I found this relevant code:
![image](https://github.com/Venipa/ytmdesktop2/assets/45090858/bc6dcd9e-4a0f-4c80-b28c-40cf3077449a)
So it does seem that Discord recently added support for the listening type enum, having it properly set your status as 'Listening to.'
![image](https://github.com/Venipa/ytmdesktop2/assets/45090858/299a9175-83f4-4bcf-90c5-b121688dce7f)
cc. @Venipa

**Comment by Venipa** [comment]
has been implemented into latest release 👍
