### ISSUE TITLE
Can i get the code for the custom theme that is enabled by default in the app

### ISSUE THREAD

**Issue by Hershey025** [Venipa/ytmdesktop2#77]
https://youtube-music.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fexample-2.b645067d.jpg&w=1920&q=75
Can you give the css code for this custom theme?

**Comment by crazygamer9597** [comment]
https://github.com/Venipa/ytmdesktop2/tree/f0c1e1ccd13bf4fabb58793c8d601abda91f7a56/src/assets
The Scss files here are the ones you are looking for ig

**Comment by Hershey025** [comment]
Thanks!
