### ISSUE TITLE
Ytmusic site update cuased an odd issue

### ISSUE THREAD

**Issue by drakosoldier298** [Venipa/ytmdesktop2#79]
### Operating system

 Microsoft Windows [Version 10.0.22621.2066]

### YouTube Music Desktop App Version

v0.10.11

### Bug description

Suddenly unable to right click anywhere in the app after the site updatedm unsure if the app also updated to use the new layout but its using it.

### Relevant log output

```shell
oddly that location doesnt exist and where my youtube music app is actually stored has no log.
```

**Comment by drakosoldier298** [comment]
found the issue, have no clue the solution, console slaps this error uppon right clicking a song or the bar.
![image](https://github.com/Venipa/ytmdesktop2/assets/30358222/185d79e8-87f4-4a38-84be-4d6c09032f81)

**Comment by Venipa** [comment]
Seems to be an issue on YouTube's side.

**Comment by drakosoldier298** [comment]
except on the website it works fine
