### ISSUE TITLE
Scroll on volume slider

### ISSUE THREAD

**Issue by sameerdash2** [Venipa/ytmdesktop2#80]
**Is your feature request related to a problem? Please describe.**
Minor inconvenience, it can be hard to precisely control the volume.

**Describe the solution you'd like**
YouTube music website lets you scroll over the volume slider to shift it by 10% per scroll notch:

https://github.com/Venipa/ytmdesktop2/assets/73513725/e7afa1d3-6f1e-4f05-96f6-55cc19a40e1a

This would be nice to have.

Cool app 👍

**Comment by Pyseph** [comment]
Agreed, would be a great UX feature.
