### ISSUE TITLE
Windows 11 miniplayer can't display info about the music or doesn't show up at all.

### ISSUE THREAD

**Issue by kastentop2005** [Venipa/ytmdesktop2#86]
### Operating system

Microsoft Windows [Version 10.0.22621.2506]

### YouTube Music Desktop App Version

v0.10.11

### Bug description

See on the screenshot:
https://i.imgur.com/gIYkA9u.png

### Steps to reproduce

Just play a song

### Relevant log output

```shell
Can't find it
```

**Comment by Venipa** [comment]
@kastentop2005 this has been fixed with the latest release
