### ISSUE TITLE
Discord Rich Presence Timestamp

### ISSUE THREAD

**Issue by JDTHEPS** [Venipa/ytmdesktop2#89]
**Is your feature request related to a problem? Please describe.**
The current Discord Rich Presence timestamp on YouTube Music Desktop only displays the time left of a song, which can sometimes be limiting for users who want a better understanding of their listening experience. By changing it to show the "listening time now" and "end time," users would have a clearer picture of the current point in the song and the overall duration.

**Describe the solution you'd like**
I would like to request a modification to the Discord Rich Presence timestamp on YouTube Music Desktop, so that it displays the "listening time now" and "end time" in the format of "01:12/03:45". This change would provide users with valuable information about their listening progress and the remaining duration of the song.

**Describe alternatives you've considered**
I have considered alternative solutions, but none of them offer the same level of clarity and functionality as the proposed modification. The suggested format of "01:12/03:45" would enable users to easily comprehend their current listening time and the total duration of the song.

**Additional context**
I understand that implementing this feature may depend on various factors, including technical feasibility and compatibility with the YouTube Music Desktop application. I would greatly appreciate it if you could provide me with any information or insights regarding the possibility of incorporating this modification into the Discord Rich Presence timestamp feature on YouTube Music Desktop.

_Thank you for your attention to this matter._

**Comment by Venipa** [comment]
> **Is your feature request related to a problem? Please describe.** The current Discord Rich Presence timestamp on YouTube Music Desktop only displays the time left of a song, which can sometimes be limiting for users who want a better understanding of their listening experience. By changing it to show the "listening time now" and "end time," users would have a clearer picture of the current point in the song and the overall duration.
> 
> **Describe the solution you'd like** I would like to request a modification to the Discord Rich Presence timestamp on YouTube Music Desktop, so that it displays the "listening time now" and "end time" in the format of "01:12/03:45". This change would provide users with valuable information about their listening progress and the remaining duration of the song.
> 
> **Describe alternatives you've considered** I have considered alternative solutions, but none of them offer the same level of clarity and functionality as the proposed modification. The suggested format of "01:12/03:45" would enable users to easily comprehend their current listening time and the total duration of the song.
> 
> **Additional context** I understand that implementing this feature may depend on various factors, including technical feasibility and compatibility with the YouTube Music Desktop application. I would greatly appreciate it if you could provide me with any information or insights regarding the possibility of incorporating this modification into the Discord Rich Presence timestamp feature on YouTube Music Desktop.
> 
> _Thank you for your attention to this matter._

I don't think that's possible for discord rich presence interface
