### ISSUE TITLE
Packaging for ARM64 and installing to ARM64

### ISSUE THREAD

**Issue by JustAnEric** [Venipa/ytmdesktop2#91]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when something isn't supported or won't build on unsupported platforms (looking at you Kali Linux on ARM)
Is there a way currently out there to install YT Music on ARM64 (aarch64) builds of Linux, or not?
Also just to throw in, I tried installing and building from `yarn` but that didn't seem to work.

**Comment by Venipa** [comment]
@JustAnEric i made a pre release with arm builds for all platforms, https://github.com/Venipa/ytmdesktop2/releases/tag/v0.11.9
still in testing tho

**Comment by JustAnEric** [comment]
amazing, I will gladly test it out on my Kali Linux machine, thanks so much.
