### ISSUE TITLE
I can't use my google account

### ISSUE THREAD

**Issue by FingFilm15** [Venipa/ytmdesktop2#96]
### Operating system

 Microsoft Windows [Version 10.0.22631.2861]

### YouTube Music Desktop App Version

v0.10.11

### Bug description

Hi! I cant sign into my google account because it says: "This browser or app may not be secure." I used to use a different youtube music app but i decided to switch to this so i dont know what to do.
![image](https://github.com/Venipa/ytmdesktop2/assets/112880596/bafa4034-eb11-44a5-bb2a-c45f53d5058f)

**Comment by Venipa** [comment]
@FingFilm15 for now press "try again" until the signin works, it's Google's fault on this one

**Comment by dszilagyi012** [comment]
In youtube music search for Help and in the 9 dots in the right top corner and search GMAil and now you can log-in!

**Comment by Vardorien** [comment]
Managed to log-in by choosing the option to get YouTube premium. Opened a valid login page.

**Comment by Jacexm** [comment]
> Managed to log-in by choosing the option to get YouTube premium. Opened a valid login page.

it's work!

**Comment by Venipa** [comment]
newest pre release [0.12.1](https://github.com/Venipa/ytmdesktop2/releases/tag/v0.12.1) shows more information on this matter
instead of people creating new issues on here
