### ISSUE TITLE
Installed v0.11.9, it says the version is 0.11.6

### ISSUE THREAD

**Issue by Syhmac** [Venipa/ytmdesktop2#97]
### Operating system

 Microsoft Windows [Version 10.0.22635.3286]

### YouTube Music Desktop App Version

v.0.11.9

### Bug description

I have installed version 0.11.9, but app thinks it's 0.11.6 and it bothers me all the time with update. When I try to update it restarts, but still says it's 0.11.6.

There is no logs file in the installation directory 

### Steps to reproduce

1. Download YouTube-Music-for-Desktop-0.11.9_x64.exe
2. Install it
3. Open app

And it should say it's at version 0.11.6

**Comment by D99-1** [comment]
Same issue on MacOs 14.1 (23B74)

Not updating, had to manually install from github

**Comment by Venipa** [comment]
0.11.9 is a prerelease with new builded platform flags, it may cause issues while upgrading from stable

**Comment by Syhmac** [comment]
Yeah, but I wasn't upgrading from stable. I tried to install it from provided instalator.

**Comment by Venipa** [comment]
> Yeah, but I wasn't upgrading from stable. I tried to install it from provided instalator.

i added a note to the pre release that its required to download from github instead the of the stable updater.
due to changes made on the building parameters..
