### ISSUE TITLE
play/pause button doesn't work in mini player

### ISSUE THREAD

**Issue by Syhmac** [Venipa/ytmdesktop2#99]
### Operating system

 Microsoft Windows [Version 10.0.22635.3286]

### YouTube Music Desktop App Version

v.0.11.6 / v.0.11.9

### Bug description

When I go to mini player the play/pause button doesn't work. It can pause, but it doesn't change to play and you can't resume music.

I placed two app version. It's related to the other bug report I created. I installed 0.11.9, but app says it's 0.11.6

### Steps to reproduce

1. Open app
2. Start listening to anything
3. Open mini player
4. Click pause button
5. Clicking it again will have no effect

### Relevant log output

```shell
No logs in installation folder
```

**Comment by Venipa** [comment]
@Syhmac hmm i dont know but it seems im unable to reproduce it

https://github.com/Venipa/ytmdesktop2/assets/17952364/132bdd2c-6aa3-49c4-9c5a-bb923c47952b

**Comment by Syhmac** [comment]
Hmm... Actually I can't do it as well. Maybe I did something else. I will look into it once it will break again, cause it started working.
